##### Setup For Postgres #####
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true